### ISSUE TITLE
text.claimchunk.claimed is not translated

### ISSUE THREAD

**Issue by Blayyke** [maciekkkkkkk/ClaimChunk#4]

**Comment by Blayyke** [comment]
https://i.imgur.com/QExZyEl.png

**Comment by Blayyke** [comment]
Neither is /cinfo https://i.imgur.com/9T5Xb7M.png
(there should also probably be a dot between owner and my name)

**Comment by FollowTM** [comment]
weird, will be fixed in new version

**Comment by Blayyke** [comment]
Alright, so I downloaded the source and threw my own build.gradle and gradlew stuff in there because you seem to have it .gitignore'd, and running in a dev environment, the names show up translated. I built the mod and threw it in all-of-fabric and it is back to showing translation keys. Fabric bug?

**Comment by RealCorebb** [comment]
Did you fix that?
